name: Update Electricity Prices

on:
  schedule:
    - cron: '0 */1 * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas pytz
          
      - name: Run price update script
        run: python scripts/update_fallback_data.py
        # Add this under the "Run price update script" step
        env:
          ENTSOE_API_KEY: ${{ secrets.ENTSOE_API_KEY }}
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update electricity prices fallback data" && git push)